import { Montserrat, Poppins } from "next/font/google";
import "./globals.css";

const montserrat = Poppins({ weight: ["400", "500", "600", "700", "800", "900"], subsets: ["latin-ext"]});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>{children}</body>
    </html>
  );
}
